---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-daddy
  namespace: big-daddy
  labels:
    app: big-daddy
    env: staging
    microservice: big-daddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: big-daddy
      env: staging
      microservice: big-daddy
  template:
    metadata:
      labels:
        app: big-daddy
        env: staging
        microservice: big-daddy
    spec:
      containers:
      - name: big-daddy
        image: scurran1479/big_daddy:0.2
        imagePullPolicy: IfNotPresent
        command: ["python3", "run_flask.py"]
        ports:
        - name: api
          containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /service/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /service/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
